#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/pdx223

PRODUCT_COPY_FILES += \
    vendor/sony/pdx223/proprietary/odm/etc/customization/XQ-CT44/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-CT44/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/XQ-CT54/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-CT54/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/XQ-CT54_EEA/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-CT54_EEA/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/XQ-CT62/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-CT62/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/XQ-CT72/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-CT72/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/XQ-CT72_RU/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-CT72_RU/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c000002/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000002/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c000018/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000018/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c000027/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000027/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c000032/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000032/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c001435/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001435/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c001492/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001492/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c001526/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001526/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c001678/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001678/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c001707/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001707/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c001839/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001839/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c001884/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001884/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c999990/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999990/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c999996/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999996/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c999997/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999997/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c999998/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999998/config.prop \
    vendor/sony/pdx223/proprietary/odm/etc/customization/c999999/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999999/config.prop \
    vendor/sony/pdx223/proprietary/vendor/camera/CAMINO_FW_DATA_AF_0x0104.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CAMINO_FW_DATA_AF_0x0104.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/CAMINO_FW_DATA_OIS_0x0101.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CAMINO_FW_DATA_OIS_0x0101.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/CASTORE_FW_DATA_1_0x16813030.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CASTORE_FW_DATA_1_0x16813030.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/CASTORE_FW_DATA_2_0x16813030.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CASTORE_FW_DATA_2_0x16813030.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/CASTORE_FW_DATA_4_0x16813030.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CASTORE_FW_DATA_4_0x16813030.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/CASTORE_FW_DATA_5_0x16813030.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CASTORE_FW_DATA_5_0x16813030.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/color_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/dataflow.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/depth_measurement.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/depth_measurement.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/dual_bokeh_comp.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/exposure_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/exposure_ctrl_diagram.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/exposure_ctrl_diagram_z.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/exposure_ctrl_diagram_z.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/eye_stabilizer.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/face_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/face_detector_soda.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/flicker_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/food_comp_yummy.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/hal_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/hal_ctrl_ipe_ica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/hal_ctrl_ipe_ica.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/hdr_comp.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/idt_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_cheesescone.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_marble.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_raisin.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_zunda.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/lens_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/lens_ctrl_common.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/main_subject_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/main_subject_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/motion_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/motion_detector_sumomo.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/motion_estimation.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/object_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/object_tracker.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/prc_image_conv.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/raw_conv_parisbrest.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/raw_proc_platform.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/LGI12BC0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/scene_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/color_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/dataflow.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/depth_measurement.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/depth_measurement.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/dual_bokeh_comp.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/exposure_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/exposure_ctrl_diagram.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/exposure_ctrl_diagram_z.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/exposure_ctrl_diagram_z.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/eye_stabilizer.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/face_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/face_detector_soda.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/flicker_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/food_comp_yummy.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/hal_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/hal_ctrl_ipe_ica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/hal_ctrl_ipe_ica.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/hdr_comp.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/idt_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/image_conv.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/image_conv_cheesescone.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/image_conv_marble.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/image_conv_raisin.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/image_conv_zunda.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/lens_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/lens_ctrl_common.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/main_subject_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/main_subject_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/motion_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/motion_detector_sumomo.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/motion_estimation.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/object_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/object_tracker.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/prc_image_conv.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/raw_conv_parisbrest.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/raw_proc_platform.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC4/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC4/scene_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/color_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/dataflow.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/depth_measurement.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/depth_measurement.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/dual_bokeh_comp.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/exposure_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/exposure_ctrl_diagram.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/exposure_ctrl_diagram_z.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/exposure_ctrl_diagram_z.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/eye_stabilizer.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/face_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/face_detector_soda.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/flicker_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/food_comp_yummy.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/hal_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/hal_ctrl_ipe_ica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/hal_ctrl_ipe_ica.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/hdr_comp.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/idt_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/image_conv.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/image_conv_cheesescone.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/image_conv_marble.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/image_conv_raisin.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/image_conv_zunda.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/lens_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/lens_ctrl_common.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/main_subject_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/main_subject_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/motion_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/motion_detector_sumomo.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/motion_estimation.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/object_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/object_tracker.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/prc_image_conv.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/raw_conv_parisbrest.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/raw_proc_platform.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/SEM12BC5/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC5/scene_detector.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/data.zip:$(TARGET_COPY_OUT_VENDOR)/camera/data.zip \
    vendor/sony/pdx223/proprietary/vendor/camera/default.dat:$(TARGET_COPY_OUT_VENDOR)/camera/default.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/display_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/display_ctrl.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/optical_axis.dat:$(TARGET_COPY_OUT_VENDOR)/camera/optical_axis.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/snapshot.dat:$(TARGET_COPY_OUT_VENDOR)/camera/snapshot.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/streaming.dat:$(TARGET_COPY_OUT_VENDOR)/camera/streaming.dat \
    vendor/sony/pdx223/proprietary/vendor/camera/supported.dat:$(TARGET_COPY_OUT_VENDOR)/camera/supported.dat \
    vendor/sony/pdx223/proprietary/vendor/etc/acdbdata/waipio_qrd/Sony_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/waipio_qrd/Sony_acdb_cal.acdb \
    vendor/sony/pdx223/proprietary/vendor/etc/acdbdata/waipio_qrd/Sony_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/waipio_qrd/Sony_workspaceFileXml.qwsp \
    vendor/sony/pdx223/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/sony/pdx223/proprietary/vendor/etc/display/qdcm_calib_data_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_1.json \
    vendor/sony/pdx223/proprietary/vendor/etc/displayconfig/display_port_129.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_port_129.xml \
    vendor/sony/pdx223/proprietary/vendor/etc/init/vendor.somc.hardware.camera.provider@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.somc.hardware.camera.provider@1.0-service.rc \
    vendor/sony/pdx223/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/sony/pdx223/proprietary/vendor/etc/libhdr_somc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/libhdr_somc.xml \
    vendor/sony/pdx223/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/sony/pdx223/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/sony/pdx223/proprietary/vendor/etc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_RF.conf \
    vendor/sony/pdx223/proprietary/vendor/etc/sensors/config/waipio_ak991x_0_somc_product.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_ak991x_0_somc_product.json \
    vendor/sony/pdx223/proprietary/vendor/etc/wifi/bdwlan.e8d:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.e8d \
    vendor/sony/pdx223/proprietary/vendor/etc/wifi/bdwlang.e8d:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlang.e8d \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_44k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_48k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_44k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_48k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_44k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_48k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_default_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_44k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_default_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_48k.tbl \
    vendor/sony/pdx223/proprietary/vendor/etc/zoom_noise_reduction/znr_parameter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_parameter.xml \
    vendor/sony/pdx223/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/sony/pdx223/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/sony/pdx223/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/sony/pdx223/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/sony/pdx223/proprietary/vendor/firmware/L-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l41-dsp1-spk-cali.bin \
    vendor/sony/pdx223/proprietary/vendor/firmware/L-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l41-dsp1-spk-prot.bin \
    vendor/sony/pdx223/proprietary/vendor/firmware/R-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l41-dsp1-spk-cali.bin \
    vendor/sony/pdx223/proprietary/vendor/firmware/R-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l41-dsp1-spk-prot.bin \
    vendor/sony/pdx223/proprietary/vendor/firmware/touch_module_id_0x46.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x46.img \
    vendor/sony/pdx223/proprietary/vendor/firmware/tzwidevine.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.mbn \
    vendor/sony/pdx223/proprietary/vendor/firmware/tzwvcpybuf.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.mbn \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.sensormodule.camino_imx650.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.camino_imx650.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.sensormodule.castore_imx557.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.castore_imx557.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.sensormodule.castore_imx563.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.castore_imx563.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.sensormodule.icarus_imx316.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.icarus_imx316.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.tuned.camino_imx650.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.camino_imx650.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.tuned.castore_imx557.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.castore_imx557.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.tuned.castore_imx563.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.castore_imx563.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.tuned.crocus_imx663.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.crocus_imx663.bin \
    vendor/sony/pdx223/proprietary/vendor/lib64/camera/com.sony.tuned.icarus_imx316.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.icarus_imx316.bin

PRODUCT_PACKAGES += \
    com.qti.eeprom.gt24p128c2csli_imx766 \
    com.qti.eeprom.irs2381c_polar \
    com.qti.eeprom.truly_cmb433 \
    com.qti.ois.bu63169gwz \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx334 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx363 \
    com.qti.sensor.imx376 \
    com.qti.sensor.imx386 \
    com.qti.sensor.imx476 \
    com.qti.sensor.imx481 \
    com.qti.sensor.imx519 \
    com.qti.sensor.imx563 \
    com.qti.sensor.imx576 \
    com.qti.sensor.imx577 \
    com.qti.sensor.imx586 \
    com.qti.sensor.imx588 \
    com.qti.sensor.imx686 \
    com.qti.sensor.imx766 \
    com.qti.sensor.max7366_6dof \
    com.qti.sensor.max7366_eyetrack \
    com.qti.sensor.max7366_ov6211 \
    com.qti.sensor.max7366_ov9282 \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov12a10_front \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov6211_master \
    com.qti.sensor.ov6211_slave \
    com.qti.sensor.ov7251 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.ov8856_master \
    com.qti.sensor.ov8856_slave \
    com.qti.sensor.ov9282_master \
    com.qti.sensor.ov9282_slave \
    com.qti.sensor.s5k2l7 \
    com.qti.sensor.s5k2x5sp \
    com.qti.sensor.s5k33dxx \
    com.qti.sensor.s5k3m5 \
    com.qti.sensor.s5k3p9 \
    com.qti.sensor.s5k4h7 \
    com.qti.sensor.s5k5e9yu05 \
    com.qti.sensor.s5k5e9yx04 \
    com.qti.sensor.s5kjd1sp \
    com.bots.node.vendortagwrite \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper \
    libdepthmapwrapper_secure \
    libexcal_ckb_service_plugin \
    libexcal_color_ctrl_plugin \
    libexcal_debug_display_plugin \
    libexcal_depth_comp_plugin \
    libexcal_depth_measurement_plugin \
    libexcal_draw_comp_plugin \
    libexcal_dual_bokeh_comp_plugin \
    libexcal_exposure_analyzer_plugin \
    libexcal_exposure_ctrl_plugin \
    libexcal_eye_stabilizer_plugin \
    libexcal_face_detector_plugin \
    libexcal_flicker_detector_plugin \
    libexcal_food_comp_plugin \
    libexcal_hal_ctrl_plugin \
    libexcal_hdr_plugin \
    libexcal_idt_ctrl_plugin \
    libexcal_image_conv_plugin \
    libexcal_iq_ctrl_plugin \
    libexcal_jpeg_enc_plugin \
    libexcal_lens_ctrl_plugin \
    libexcal_main_subject_detector_plugin \
    libexcal_motion_detector_plugin \
    libexcal_motion_estimation_plugin \
    libexcal_object_detector_plugin \
    libexcal_object_tracker_plugin \
    libexcal_prc_image_conv_plugin \
    libexcal_raw_conv_plugin \
    libexcal_raw_dump_plugin \
    libexcal_raw_proc_plugin \
    libexcal_req_ctrl_plugin \
    libexcal_scene_detector_plugin \
    libexcal_single_bokeh_comp_plugin \
    libexcal_snapshot_ctrl_plugin \
    libexcal_splitter_plugin \
    libexcal_stream_ctrl_plugin \
    camx.device@3.2-impl \
    camx.device@3.3-impl \
    camx.device@3.4-ext-impl \
    camx.device@3.4-impl \
    camx.device@3.5-ext-impl \
    camx.device@3.5-impl \
    camx.device@3.6-ext-impl \
    camx.device@3.6-impl \
    camx.device@3.7-impl \
    camx.provider@2.4-external \
    camx.provider@2.4-impl \
    camx.provider@2.4-legacy \
    camx.provider@2.5-external \
    camx.provider@2.5-legacy \
    camx.provider@2.6-legacy \
    camx.provider@2.7-legacy \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.cedros \
    com.qti.feature2.gs.fillmore \
    com.qti.feature2.gs.sdm865 \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.gs.sm8450 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr.sm8450 \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.fillmore \
    com.qti.settings.sm8450 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.xr \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    com.qti.chi.override \
    libaidenoiser \
    libarcsoft_bokeh_adapter \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_dualcam_refocus_video \
    libarcsoft_hdr_adapter \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libbitmlengine \
    libbitmlenginev2 \
    libcamera2ndk_vendor \
    libcamera_nn_stub \
    libcamerapostproc \
    libcammw \
    libcammw_util \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnnvendor \
    libcapiv2svarnnvendor \
    libcapiv2uvvendor \
    libchilog \
    libcom.qti.chinodeutils \
    libdepthcomputation \
    libexcal_core \
    libexcal_system \
    libhdr10plus \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libiu456_datapath_processor \
    libjpege \
    libmctfengine_stub \
    libmfGhostDetection \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmorpho_single_camera \
    libmpbase \
    libopencv \
    libopencv3a \
    libopenvx \
    libopestriping \
    libos \
    libqll \
    libqll10 \
    libqllengine \
    libqshcamera \
    libsfeShiftExtrapolation \
    libsomc_aerial \
    libsomc_alfortlpserv \
    libsomc_angelpie \
    libsomc_avan \
    libsomc_buttercake \
    libsomc_buttercakersc \
    libsomc_camerahal \
    libsomc_camerapal \
    libsomc_cheesescone \
    libsomc_cheesesconersc \
    libsomc_chokoballcmn \
    libsomc_chokoballkeymgr \
    libsomc_chokoballpal \
    libsomc_cornfrosty \
    libsomc_dai \
    libsomc_donutscmnserv \
    libsomc_drops \
    libsomc_dropsrsc \
    libsomc_facewrapper \
    libsomc_flicker \
    libsomc_formatconverter \
    libsomc_formatconverterrsc \
    libsomc_madeleinebase \
    libsomc_marble \
    libsomc_marblersc \
    libsomc_oshirukoserv \
    libsomc_parisbrest \
    libsomc_parisbrestrsc \
    libsomc_pdnserv \
    libsomc_pretzchoco \
    libsomc_pretzchocorsc \
    libsomc_raisin \
    libsomc_raisincl \
    libsomc_raisinclrsc \
    libsomc_raisinrsc \
    libsomc_sheera \
    libsomc_shortcake \
    libsomc_shortcakersc \
    libsomc_soda \
    libsomc_sukonbu \
    libsomc_sumomo \
    libsomc_sumomorsc \
    libsomc_thermal \
    libsomc_wasabeef \
    libsomc_yummy \
    libsomc_yummyrsc \
    libsomc_zunda \
    libsony_animaleye \
    libsony_asr \
    libsony_cc \
    libsony_ec \
    libsony_facestab \
    libsony_fc \
    libsony_naruto \
    libsony_stab \
    libspectre \
    libswregistrationalgo \
    libsynx \
    libtfestriping \
    libthreadutils \
    libubifocus \
    local_libcamera_metadata \
    vendor.qti.hardware.camera.aon@1.0-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.somc.camera.device@3.2-impl \
    vendor.somc.camera.device@3.3-impl \
    vendor.somc.camera.device@3.4-impl \
    vendor.somc.camera.device@3.5-impl \
    vendor.somc.hardware.camera.provider.manifest.xml \
    vendor.somc.hardware.camera.provider@1.0-service

PRODUCT_PACKAGES += \
    vendor_firmware_bdwlan_e8d \
    vendor_firmware_bdwlang_e8d
